### ISSUE TITLE
Consistent use of dashes: Q-bit or Q bit?

### ISSUE THREAD

**Issue by dtikhonov** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#10]
Let's settle on one way and make the draft consistent in this regard.

My preference would be _not_ to use the dash.

**Comment by igorlord** [comment]
I am ok with that.

A related issue is the use of "QL bits" vs "loss bits".  What's your take on that?

**Comment by dtikhonov** [comment]
One issue with the naming I've been having (in my code) regarding "QL bits" vs "QL loss bits" vs "loss bits" is that L is the loss bit and, at the same time, together they are loss bits.

Certainly, the expression "loss bits" is a better name for the Draft.  (Compare with "QL bits.")  One way to approach this is to rename the L "the **Loss** event bit" to E "the loss **Event** bit.  Then Q and E together will be the loss bits.

Short of that, I'd drop the use of "QL bits" in favor of "loss bits" everywhere in the draft.

**Comment by igorlord** [comment]
I think I've replaced "loss bit" with "loss event bit" everywhere before.  I'd say we ought to keep "Loss event bit" L, since it is very mnemonic.  Replacing "QL-?bits with" "loss bits" seems right.

**Comment by dtikhonov** [comment]
I'll make a PR for this.
