### ISSUE TITLE
0x1055 is not a valid TP number

### ISSUE THREAD

**Issue by igorlord** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#15]
Not valid per "QUIC Transport Parameter Registry" in the transport draft, since 0x1055 == 134*31+27.  Damn, there was a 26/27 chance, and we blew it!

**Comment by dtikhonov** [comment]
Wow, good catch!

Too bad: "loss" is an excellent mnemonic device.  One the bright size, "lost" is only 2 away: 0x1057.

**Comment by ferrieux** [comment]
@igorlord: you mean 30/31 but, indeed, too bad :)

Out of curiosity: where does this blacklisting of 27 modulo 31 come from ?

**Comment by dtikhonov** [comment]
0x8175: "bits"

**Comment by igorlord** [comment]
@dtikhonov Let's go with 0x1057.

@ferrieux The specific formula -- do not remember where it came from.

**Comment by igorlord** [comment]
Resolved via #16
