### ISSUE TITLE
What happens to L in DATAGRAM mode ?

### ISSUE THREAD

**Issue by ferrieux** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#18]
While considering opt-ack mitigation and the possible associated noise on Q, the distinction between normal (STREAM) and DATAGRAM modes came up. As it turns out, an "unpolluted" Q is of concern only for DATAGRAM (since for stream, stream progression gives the same info).

Now, how would the L bit be computed in the DATAGRAM case ? L is supposed to be low-hanging fruit for a "loss detection machinery", which is the algorithm driving the lifecycle of packets in the retrans queue. But DATAGRAMs don't have a retrans queue, right ?

If it turns out that L cannot be defined for DATAGRAM, we may be better off disabling lossbits altogether in that case. Ipso facto, in the STREAM case, noisy-Q (decrement when mitigating opt-ack) is unneeded. 

Am I missing something ?

**Comment by igorlord** [comment]
I do not understand the problem.  DATAGRAM is an ACK-eliciting frame (it has to be for the congestion controller to work).  So loss of packets containing DATAGRAMs is known to the sender (who will likely not retransmit lost DATAGRAMs, but that's an orthogonal concern).

**Comment by dtikhonov** [comment]
I agree with Igor:  A lost packet is a lost packet.

**Comment by ferrieux** [comment]
OK, but being ACK-eliciting does not imply full lifecycle handling like would be needed for a retrans queue. If the API uses QUIC packet numbers as identifiers (one in return from a "send", and one passed to the ack callback), then the stack itself can remain entirely stateless. In this case, there is no such thing as a timer deciding that a given PN is lost. For L to work, this logic must then be added.

**Comment by igorlord** [comment]
@ferrieux I am still unsure what logic needs to be added to the stack.  If the receiver stack received a valid packet, it will ACK it in due time.  If that packet contained an ACK-eliciting frame, the ACK will have a tight "deadline" when it must go out (if the packet contained no ACK-eliciting frames, the ACK may be delayed significantly). DATAGRAM is an ACK-eliciting frame. 

The sender will know which packets were lost with the same degree of reliability, regardless of whether the packets contained STREAM or DATAGRAM frames.  It can maintain L counter equally well when DATAGRAM is used.

What am I missing?

**Comment by ferrieux** [comment]
Oh, you mean that the DATAGRAM frames must keep enough state (similar to retrans queue entries) until their ACK arrives in order to feed the congestion control ? Ok, i n that case, indeed, L is a no-brainer, since these entries will have an expiration timeout (at which time an L=1 is emitted).

Now, in a QUIC-in-QUIC (or TCP-in-QUIC) scenario, where QUIC datagrams encapsulate an L4 with its own congestion control, I guess we want the container-QUIC's congestion control to be disabled. In that case, will the entry expiration timeout still exist ?

**Comment by igorlord** [comment]
> Oh, you mean that the DATAGRAM frames must keep enough state [...].

Yes, except congestion state (and hence ACKing) is "attached" not to QIUC frames (like DATAGRAM) but to QUIC packets.

> Now, in a QUIC-in-QUIC (or TCP-in-QUIC) scenario, [...]

This is no different from any A-in-B scenario.  Both inner and outer protocols operate independently from each other (other the other protocol enforcing some PMU on the inner protocol).  Of course, depending on B, A may experience "interesting" network properties.

**Comment by ferrieux** [comment]
> Both inner and outer protocols operate independently from each other

Well, cascading two BBRs or two Cubics is not really desirable, so I imagined some API to disable congestion control in the outer (datagram-bearing) QUIC...
