### ISSUE TITLE
organization of the document

### ISSUE THREAD

**Issue by NicoKos** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#34]
The document jumps from Introduction to the solution. A motivation section could help design the scope of the observer and what it can see and cannot. 

I think a motivation section could help identifying what is needed and the rationale behind the Q and I bits. 

This would also help in detailing what is the rationale behind each of Q and I.

**Comment by igorlord** [comment]
Thanks for the feedback.  I think we used Introduction largely for motivation.  Is there something you can recommend we talk about in the Motivation section?  Or do you have a suggestion on what to leave in the Introduction and what to move to the Motivation?

**Comment by NicoKos** [comment]
I proposed some text update in PR #36

**Comment by igorlord** [comment]
Resolved by #36
