### ISSUE TITLE
Simple questions for the security section ?

### ISSUE THREAD

**Issue by NicoKos** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#35]
Is it relevant to add simple questions in the security section ?

"What can the observer see?"
"Is it possible that an observer correlate past/current connections?"

**Comment by igorlord** [comment]
Do you have some ideas for what you'd like to see for those questions?

**Comment by NicoKos** [comment]
after a better reading of the security section it looks to me that there is no need to go deeper into such details.
