### ISSUE TITLE
Q-bit: little or no new information?

### ISSUE THREAD

**Issue by dtikhonov** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#7]
> For QUIC v1 connections, the attacker can examine offsets in STREAM frames to determine whether packet number skips are deliberate, so Q-bit signal provides little new information.

Why "little" instead of "no?"  AFAICT, the Q-bit provides no new information.

**Comment by igorlord** [comment]
I was worried that someone will have some far-fetched objection to "no", which would lead a rat hole for the discussion.  For example, there may be cases when a lost packet had a STREAM frame for a new stream, so it would not be noticed.

But I may actually agree to "no", since what we care about is a signal that something has definitely been lost.  The example above only informs that something might be lost (but likely is a deliberate skip).

**Comment by dtikhonov** [comment]
My problem with the current phrasing, "provides little new information," is that it leads the reader to ask "*what* new information does the Q bit provide?"  This is not covered in the draft.  I'd replace "little" with "no" for clarity.

Another way to handle this is to rephrase along these lines:

> The information exposed by the square wave value with regard to artificial packet number gaps can be gleaned by other means.  For example, the attacker can analyze offsets in STREAM frames to detect holes.

Since this discussion is in the context of an opt-ACK attack, which requests a large resource, this makes sense.

**Comment by ferrieux** [comment]
In the same vein, but in the introductory paragraph of the same section, isn't the sentence "_...does not provide any information that cannot be observed by simply counting packets_" a bit of an overstatement ? Wouldn't the devil's advocate say something like "Then why do you need it in the first place ?" ?

What about "provides very little information over what can be gleaned from simply counting packets" ?

**Comment by dtikhonov** [comment]
> Since this discussion is in the context of an opt-ACK attack, which requests a large resource, this makes sense.

I take it back.  When thinking about this originally, I had HTTP/3 in mind specifically.  In HTTP/3, a large resource is delivered using a single stream.  Future application protocols that use QUIC may use multiple streams and so the "look for STREAM holes" is not applicable.  @igorlord's [comment above](https://github.com/igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits/issues/7#issuecomment-572699499) sort of touches on this.

**Comment by igorlord** [comment]
@dtikhonov, I think the key is whether the attacker is able to get the peer to send a single very large stream.  If so, the attacker has a reliable way to identify lost packets.  If not, it becomes harder for the attacker to replicate signal quality available from the Q bit.

@ferrieux Your comment about the first sentence makes sense. I'll reword it.

**Comment by igorlord** [comment]
Resolved via #12
