### ISSUE TITLE
Including skipped packet number into Q run

### ISSUE THREAD

**Issue by dtikhonov** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#8]
> However, an endpoint that implements {{DATAGRAM}} and uses a loss-based congestion controller MAY include deliberately skipped packet numbers in the current Q run.

This is confusing.  What does it mean to include skipped packet numbers in the Q run?

I suggest using a more explicit recommendation.  For example:

> To make skipped packet numbers indistinguishable from packet loss, a sender MAY shorten the current Q run by the number of skipped packets.  For example, skipping a single packet number will invert the sQuare wave one outgoing packet sooner.

**Comment by igorlord** [comment]
I like this. I do think this is still valuable to mention {{DATAGRAM}} and loss-based congestion controller.  (We can discuss this, of course).

**Comment by dtikhonov** [comment]
I think it's better if you made this change -- I think you have a better grasp of the concepts involved.

**Comment by ferrieux** [comment]
Chiming in 4 days late, sorry: Isn't the sentence "_...does not provide any information that cannot be observed by simply counting packets_" a bit of an overstatement ? Wouldn't the devil's advocate say something like "Then why do you need it in the first place ?" ?

What about "provides very little information over what can be gleaned from simply counting packets" ?

**Comment by dtikhonov** [comment]
That's a good observation -- it deserves its own issue.

**Comment by ferrieux** [comment]
Oh, right, wrong thread. I added it to the end of #7 , which seems to be better suited.

**Comment by igorlord** [comment]
Resolved via #12
