### ISSUE TITLE
Settle on the use of the definite article

### ISSUE THREAD

**Issue by dtikhonov** [igorlord/draft-ferrieuxhamchaoui-tsvwg-lossbits#9]
Sometimes the draft uses the definite article when taking about the Q and L bits (e.g. "The Q-bit signal does not provide...") and sometimes it does not (e.g "To use Q-bit for this purpose").

We should pick one way of doing it and stick with it.

I am not a native speaker.  That being said, I believe in most places where "the" is omitted, it should be used.

**Comment by igorlord** [comment]
Omg.  This is my worst nightmare -- getting the articles right.  None of us are native speakers. LOL.
I think you are right.  Could you fix this?

I might show this to native speakers closer to when we are done and ask them to fix the articles.  I might use my kid for this. :)

**Comment by dtikhonov** [comment]
I'll make a PR and do my  best.

Using child labor is a good idea, +1.

**Comment by igorlord** [comment]
Resolved in PR #13
